### ISSUE TITLE
AutoComplete for PHPStorm

### ISSUE THREAD

**Issue by francoisauclair911** [JonPurvis/faker-stripe#18]
Hi

Thank you for your package. Do you know of any ways to allow some autocomplete for your package ?
![image](https://github.com/JonPurvis/faker-stripe/assets/14027026/29291cf2-682d-4d50-a6ab-a2b1161852b1)

**Comment by JonPurvis** [comment]
Hey @francoisauclair911 👋 

Thanks for checking out the package!

For autocompletion in PHPStorm, you could try doing something like:

```php
$stripeFaker = new Stripe($this->faker);
```

That should then give you auto completion:

![image](https://github.com/JonPurvis/faker-stripe/assets/7534029/c1d44e87-b25a-4281-b3b4-ac09fe577868)

That's a quick solution, I agree it would be nice if it had autocompletion without having to do the above, I'll certainly look into it!

**Comment by francoisauclair911** [comment]
Thanks for looking into it and for the package !

**Comment by JonPurvis** [comment]
The solution I provided still stands, so it's definitely possible to get autocompletion - going to close off this issue now.
